---
# yamllint disable rule:line-length
name: MQTT Siemens S7 Connector
version: 2.2.3
slug: mqtt-s7-connector
description: "MQTT Siemens S7 connector to integrate Siemens PLC's with Home Assistant"
url: https://github.com/dixi83/hassio-addons/mqtt-s7-connector
image: "ghcr.io/rdbtekk/mqtt-s7-connector-{arch}"
init: false
ingress: true
panel_icon: mdi:robot-industrial
panel_title: S7 Connector
ports:
  8099/tcp: 8099
ports_description:
  8099/tcp: Configuration web UI
services:
  - mqtt:need
discovery:
  - mqtt
arch:
  - aarch64
  - amd64
map:
  - addon_config:rw
options:
  log_level: warning
  config_files:
    - config.yaml
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)
  config_files:
    - str?
